sidebar_foi <- sidebarPanel(id = "custom_sidebar",
             useShinyjs(),
             style = "margin-top: -15px;
                      margin-left: 10px;
                      width:60%;
                      border-radius: 15px;
                      border-color: #4492DC;
                      box-shadow: 8px 8px 22px 2px rgba(68,146,220,1);", 
             div(style = "text-align: center;", 
                 icon("viruses", class = "fa-2x")),
             width = 4,
             tags$style(HTML('#goButton {margin-top: 10px}')),
             div(h5("Force of infection", align = "center")),
             tags$hr(),
             h5("Select an Age interval:", align = "center"),
             setSliderColor(c("#0cc1ef", "#4492DC", "#dd513e"),c(1,2,3)),
             sliderInput(inputId = "deslizador", label =  "", 
                         min = 0, max = 90, value = c(0,90)),
             
             tags$hr(),
             h5("Select a race:", align = "center"),
             materialSwitch(inputId = "race1", label = "Hispanic", status = "success", right = T, value = T),
             materialSwitch(inputId = "race2", label = "Non-Hispanic American Indian", status = "success", right = T),
             materialSwitch(inputId = "race3", label = "Non-Hispanic Asian", status = "success", right = T),
             materialSwitch(inputId = "race4", label = "Non-Hispanic Black", status = "success", right = T),
             materialSwitch(inputId = "race5", label = "Non-Hispanic White", status = "success", right = T),
             tags$hr(),
             #switchInput(inputId = "race1",
             #            label = "Non-Hispanic White",
             #            onLabel = "ON",
             #            offLabel = "OFF",
             #            onStatus = "danger",
             #            offStatus = "info", value = F),
             #selectInput(inputId = "race", #checkbox
             #            label = "Choose a race:",
             #            choices = c("Non-Hispanic White", 
             #                        "Non-Hispanic Black", 
             #                        "Other Hispanic", 
             #                        "Mexican-American", 
             #                        "Other"),
             #            multiple = T, selected = "Non-Hispanic White"),
             h5("Select a cohort:", align = "center"),
             sliderTextInput(inputId = "cohort",
                             label = "",
                             choices = c(1940:1998),
                             selected = c(1940:1998)),
             div(class = "center-switch",
                 materialSwitch(inputId = "toggleSidebar",
                                label = "Plot Settings", 
                                status = "primary")),
             div(id ="Sidebar",
                 #materialSwitch(inputId = "percs",
                 #               label = "Confidence Intervals", 
                 #               status = "primary", value = T),
                 sliderInput(inputId = "bracket", 
                             label = "", 
                             min = 0, 
                             max = 50, value = 10, ),
                 h5("Age brackets", align = "center")),
             
             actionButton(inputId = "goButton", 
                          label =  " Plot Force of Infection",
                          width = "100%", 
                          icon = icon("chart-line", "fa-lg")),
             tags$hr(),
             h5("Download data", align = "center", ),
             div(class = "button-row",
                 downloadButton(outputId = "Download_csv", label = "csv", 
                                icon = icon("file-csv", "fa-lg"), 
                                class = "butt1"),
                 downloadButton(outputId = "Download_r", label = "data", 
                                icon = icon("r-project", "fa-lg"), 
                                class = "butt2")),
)